<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;netstandard2.0</TargetFrameworks>
        <Nullable>enable</Nullable>
        <Platforms>AnyCPU</Platforms>
        <AllowUnsafeBlocks>False</AllowUnsafeBlocks>
        <OutputType>Library</OutputType>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <PropertyGroup>
        <Version>4.0.0</Version>
        <GitHash>dev</GitHash>
        <InformationalVersion>$(Version)+$(GitHash)</InformationalVersion>
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
        <PackageId>PhigrosLabs.PhiInfo.Core</PackageId>
        <Authors>PhigrosLabs</Authors>
        <Description>Phigros Info Analysis Library</Description>
        <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/PhigrosLabs/PhiInfo</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shua.UA.Core\Shua.UA.Core.csproj"/>
    </ItemGroup>
</Project>